changelog-seen = 2
[build]
# Use this directory to store build artifacts.
# You can use "$ROOT" to indicate the root of the git repository.
build-dir = "/tmp/rust-mos-build"

docs = false

[target.x86_64-unknown-linux-gnu]

# Path to the `llvm-config` binary of the installation of a custom LLVM to link
# against. Note that if this is specified we don't compile LLVM at all for this
# target.

llvm-config = "/usr/local/bin/llvm-config"
